spack:
   include:
   - packages.yaml
   - compilers.yaml
   - modules.yaml
   - config.yaml
   - $GOOSE_ROOT/configs/$NREL_CLUSTER/packages.yaml
   - $GOOSE_ROOT/configs/$NREL_CLUSTER/modules.yaml
   - $GOOSE_ROOT/configs/base/packages.yaml
   - $GOOSE_ROOT/configs/base/concretizer.yaml
   - $GOOSE_ROOT/configs/base/repos.yaml
   - $GOOSE_ROOT/configs/base/config.yaml
   view: false
   packages:
     perl:
       require: "@5.30.3"
     all:
       variants: [build_type=Release]
   modules:
     default:
       tcl:
         projections:
           all: '{compiler.name}-{compiler.version}/{name}/{version}/{hash:4}'
         hash_length: 0
         all:
           conflict:
             - '{name}'
           environment:
             set:
               '{name}_ROOT_DIR': '{prefix}'
         intel-parallel-studio:
           environment:
             set:
               INTEL_LICENSE_FILE: '28519@license-1.hpc.nrel.gov'
         include: ['cuda', 'gcc', 'go', 'llvm', 'intel-parallel-studio', 'binutils', 'pgi']
         exclude: ['%gcc']
   specs:
   - binutils+gold
   - gcc@10.4.0
   - llvm@15.0.7 +omp_debug+omp_tsan+python build_type=Release
