spack:
   view: false
   modules:
     default:
       tcl:
         intel-parallel-studio:
           environment:
             set:
               INTEL_LICENSE_FILE: '28519@license-1.hpc.nrel.gov'
         include: ['cuda', 'gcc', 'go', 'llvm', 'intel-parallel-studio', 'intel-oneapi-compilers', 'binutils']
         exclude: ['%gcc']
   include:
   - packages.yaml
   - compilers.yaml
   - modules.yaml
   - config.yaml
   - $GOOSE_ROOT/configs/$NREL_CLUSTER/packages.yaml
   - $GOOSE_ROOT/configs/$NREL_CLUSTER/modules.yaml
   - $GOOSE_ROOT/configs/$NREL_CLUSTER/config.yaml
   - $GOOSE_ROOT/configs/base/packages.yaml
   - $GOOSE_ROOT/configs/base/concretizer.yaml
   - $GOOSE_ROOT/configs/base/repos.yaml
   - $GOOSE_ROOT/configs/base/modules.yaml
   - $GOOSE_ROOT/configs/base/bootstrap.yaml
   - $GOOSE_ROOT/configs/base/config.yaml
   specs:
   - binutils
   - gcc@=12.3.0
   - intel-oneapi-compilers@=2023.2.1
