packages:
  binutils:
    require: "+ld+gas+gold"
  slurm:
    buildable: false
    require: "@=21.08.8"
    externals:
    - spec: slurm@=21.08.8
      prefix: /nopt/slurm/current
      modules:
        - slurm
  mpi:
    require: "mpt"
  mpt:
    require: "@=2.22"
    buildable: false
    externals:
    - spec: mpt@=2.22
      prefix: /opt/hpe/hpc/mpt/mpt-2.22
      modules:
        - mpt/2.22
        - slurm
  blas:
    require: "netlib-lapack"
  lapack:
    require: "netlib-lapack"
  all:
    variants: build_type=Release
    compiler: [oneapi]
