spack:
   view: false
   #view:
   #  default:
   #    root: $env/view
   #    projections:
   #      all: '{compiler.name}/{compiler.version}/{name}/{version}/{hash:8}'
   #    link_type: symlink
   modules:
     default:
       tcl:
         exclude: ['gcc', 'cuda', 'llvm', 'binutils', 'intel-oneapi-compilers']
   include:
   - packages.yaml
   - compilers.yaml
   - modules.yaml
   - config.yaml
   - $GOOSE_ROOT/configs/$NREL_CLUSTER/packages.yaml
   - $GOOSE_ROOT/configs/$NREL_CLUSTER/modules.yaml
   - $GOOSE_ROOT/configs/$NREL_CLUSTER/config.yaml
   - $GOOSE_ROOT/configs/base/packages.yaml
   - $GOOSE_ROOT/configs/base/concretizer.yaml
   - $GOOSE_ROOT/configs/base/repos.yaml
   - $GOOSE_ROOT/configs/base/modules.yaml
   - $GOOSE_ROOT/configs/base/bootstrap.yaml
   - $GOOSE_ROOT/configs/base/config.yaml
   definitions:
   - compilers: ['%gcc@=10.5.0', '%oneapi@=2023.1.0']
   - apps:
     - bc
     - bison
     - bzip2
     - cmake
     - cppcheck
     - ccls
     - curl
     - flex
     - flex@=2.5.39
     - ffmpeg
     - emacs
     - git
     - gdb
     - gnuplot+wx
     - gnutls
     - htop
     - imagemagick
     - libxml2
     - likwid
     - ninja
     - mercurial
     - makedepend
     - patch
     - pkg-config
     - python
     - rsync
     - screen
     - stow
     - strace
     - texinfo
     - texlive
     - tmux
     - unzip
     - vim
     - wget
     - zsh
     - mpt
     - osu-micro-benchmarks
     - py-numpy
     - py-matplotlib
     - py-pandas
     - py-nose
     - py-autopep8
     - py-flake8
     - py-horovod
     - py-jedi
     - py-pip
     - py-pyyaml
     - py-seaborn
     - py-sphinx
     - py-scipy
     - py-tensorflow
     - py-torch
     - py-yapf
     - py-yt
     - ninja
     - masa
     - valgrind
     - nccmp
     - netcdf-fortran
     - sundials
     - paraview
     - scotch
     - parmetis
     - amrvis dims=3
     - amrvis dims=2
   specs:
   - matrix:
     - [$apps]
     - [$compilers]
