spack:
   include:
   - packages.yaml
   - compilers.yaml
   - modules.yaml
   - config.yaml
   - $GOOSE_ROOT/configs/$NREL_CLUSTER/packages.yaml
   - $GOOSE_ROOT/configs/$NREL_CLUSTER/modules.yaml
   - $GOOSE_ROOT/configs/base/packages.yaml
   - $GOOSE_ROOT/configs/base/concretizer.yaml
   - $GOOSE_ROOT/configs/base/repos.yaml
   - $GOOSE_ROOT/configs/base/config.yaml
   view: false
   packages:
     perl:
       require: "@5.30.3"
     all:
       variants: [build_type=Release]
   modules:
     default:
       tcl:
         projections:
           all: '{compiler.name}-{compiler.version}/{name}/{version}/{hash:4}'
         hash_length: 0
         all:
           conflict:
             - '{name}'
           environment:
             set:
               '{name}_ROOT_DIR': '{prefix}'
   definitions:
   - compilers: ['%gcc@10.4.0', '%clang@15.0.7']
   - core:
     - cmake
     - emacs
     - git
     - ninja
     - screen
     - vim
     - mpt
   specs:
   - matrix:
     - [$core]
     - [$compilers]
