spack:
   include:
   - packages.yaml
   - compilers.yaml
   - modules.yaml
   - config.yaml
   - $GOOSE_ROOT/configs/$NREL_CLUSTER/packages.yaml
   - $GOOSE_ROOT/configs/$NREL_CLUSTER/modules.yaml
   - $GOOSE_ROOT/configs/$NREL_CLUSTER/config.yaml
   - $GOOSE_ROOT/configs/base/packages.yaml
   - $GOOSE_ROOT/configs/base/concretizer.yaml
   - $GOOSE_ROOT/configs/base/repos.yaml
   - $GOOSE_ROOT/configs/base/config.yaml
   view: false
   modules:
     default:
       tcl:
         projections:
           all: '{compiler.name}-{compiler.version}/{name}/{version}/{hash:4}'
         hash_length: 0
         all:
           conflict:
             - '{name}'
           environment:
             set:
               '{name}_ROOT_DIR': '{prefix}'
         exclude: ['gcc', 'llvm']
   definitions:
   - compilers: ['%gcc@10.4.0', 'intel-parallel-studio@20.0.4']
   - apps:
     - bc
     - bison
     - bzip2
     - cmake
     - cppcheck
     - curl
     - flex
     - flex@2.5.39
     - ffmpeg
     - emacs
     - git
     - gdb
     - gnuplot+wx
     - gnutls
     - htop
     - imagemagick
     - libxml2
     - likwid
     - ninja
     - mercurial
     - makedepend
     - patch
     - pkg-config
     - python
     - rsync
     - screen
     - stow
     - strace
     - texinfo
     - texlive
     - tmux
     - unzip
     - vim
     - wget
     - zsh
     - mpt
     - osu-micro-benchmarks
     - py-numpy
     - py-matplotlib
     - py-pandas
     - py-nose
     - py-autopep8
     - py-flake8
     - py-horovod
     - py-jedi
     - py-pip
     - py-pyyaml
     - py-seaborn
     - py-sphinx
     - py-scipy
     - py-tensorflow
     - py-torch
     - py-yapf
     - py-yt
     - ninja
     - masa
     - valgrind
     - nccmp
     - netcdf-fortran
     - sundials
     - paraview
     - scotch
     - parmetis
     - amrvis dims=3
     - amrvis dims=2
   specs:
   - matrix:
     - [$apps]
     - [$compilers]
