modules:
  default:
    enable: [tcl]
    tcl:
      hash_length: 0
      projections:
        all: '{compiler.name}-{compiler.version}/{name}/{version}/{hash:4}'
      all:
        conflict:
          - '{name}'
        environment:
          set:
            '{name}_ROOT_DIR': '{prefix}'
     prefix_inspections:
       lib64: [LD_LIBRARY_PATH]
     prefix_inspections:
       lib: [LD_LIBRARY_PATH]
