modules:
  prefix_inspections:
    ./lib64: 
      - LD_LIBRARY_PATH
    ./lib: 
      - LD_LIBRARY_PATH
  default:
    enable: [tcl]
    arch_folder: false
    tcl:
      hash_length: 0
      projections:
        all: '{name}/{version}/{hash:4}'
      all:
        autoload: none
        conflict:
          - '{name}'
        environment:
          set:
            '{name}_ROOT_DIR': '{prefix}'
