packages:
  blas:
    require: "openblas"
  emacs:
    require: "+tls+native+treesitter+json"
  gcc:
    require: "~bootstrap+strip languages=c,c++,fortran,jit"
  hdf5:
    require: "+hl+cxx"
  lapack:
    require: "openblas"
  llvm:
    require: "+clang+flang+python"
  texlive:
    require: "scheme=full"
  vim:
    require: "+python+cscope features=huge"
