packages:
  blas:
    require: "openblas"
  emacs:
    require: "+tls+native+treesitter+json"
  hdf5:
    require: "+hl+cxx"
  lapack:
    require: "openblas"
  llvm:
    require: "+clang+flang+python"
  vim:
    require: "+python+cscope features=huge"
  gcc:
    prefer:
     - "~bootstrap+strip languages=c,c++,fortran,jit"
  all:
    variants: build_type=Release
