modules:
  default:
    tcl:
      hash_length: 0
      all:
        autoload: none
        conflict:
          - '{name}'
        environment:
          set:
            '{name}_ROOT_DIR': '{prefix}'
      projections:
        all: '{compiler.name}-{compiler.version}/{name}/{version}/{hash:4}'
