spack:
   view: false
   include:
   - $GOOSE_ROOT/configs/ellis/packages.yaml
   - $GOOSE_ROOT/configs/ellis/modules.yaml
   - $GOOSE_ROOT/configs/ellis/config.yaml
   - $GOOSE_ROOT/configs/base/packages.yaml
   - $GOOSE_ROOT/configs/base/modules.yaml
   - $GOOSE_ROOT/configs/base/config.yaml
   definitions:
   - compilers: ["%gcc@=12.4.0"]
   - core:
     - binutils+gold
     - cuda@=12.9.0
     - cuda@=12.8.1
     - cuda@=12.6.3
     - cuda@=12.5.1
     - cuda@=12.4.1
     - cuda@=12.3.2
     - cuda@=12.2.2
     - cuda@=12.1.1
     - cuda@=11.8.0
     - cuda@=11.7.1
     - cuda@=11.6.2
     - cuda@=11.5.2
     - cuda@=11.4.4
     - gcc@=15.1.0
     - gcc@=14.3.0
     - gcc@=13.3.0
     - gcc@=12.4.0
     - gcc@=11.5.0
     - gcc@=10.5.0
     - gcc@=9.5.0
     - gcc@=8.5.0
     - go@=1.24.3
     - llvm@=20.1.5
     - llvm@=19.1.7
     - llvm@=17.0.6
     - llvm@=16.0.6
     - llvm@=15.0.7
     - llvm@=14.0.6
     - environment-modules
     - screen
     - aspell
     - bc
     - bison
     - bzip2
     - ccls
     - cmake
     - cppcheck
     - curl
     - flex
     - ffmpeg
     - fftw
     - emacs ^gcc@12.4.0
     - git
     - gdb
     - gnuplot
     - gnutls
     - htop
     - hunspell
     - imagemagick
     - libxml2
     - likwid
     - ninja
     - npm
     - mercurial
     - makedepend
     - patch
     - pkg-config
     - python
     - rsync
     - screen
     - stow
     - strace
     - texinfo
     - texlive
     - tmux
     - unzip
     - vim
     - wget
     - zsh
     - global
     - xterm
     - py-numpy
     - py-matplotlib
     - py-pandas
     - py-nose
     - py-autopep8
     - py-flake8
     - py-jedi
     - py-pip
     - py-pyyaml
     - py-seaborn
     - py-sphinx
     - py-scipy
     - py-yapf
     - py-yt
     - py-torch
     - py-tensorflow
     - masa~python
     - valgrind~mpi
     - ascent
     - nccmp
     - netcdf-fortran
     - amrvis dims=3
     - amrvis+profiling dims=2
     - mpich
     - hdf5
     - parallel-netcdf
     - paraview
     - visit
     - netcdf-c
     - boost
     - hypre
     - h5z-zfp
     - yaml-cpp
   specs:
   - matrix:
     - [$core]
     - [$compilers]
