spack:
  view: false
  concretizer:
    unify: true
    reuse: true
  config:
    source_cache: /mnt/vdb/home/$user/.spack_downloads
    build_stage: $spack/var/spack/stage
    install_tree:
      root: $spack/../install/$date/opt
  packages:
    mpi:
      require: "mpich"
    blas:
      require: "openblas"
    lapack:
      require: "openblas"
    all:
      require:
        - "build_type=Release"
        - "%[when=%c]c=gcc@12.5.0 %[when=%cxx]cxx=gcc@12.5.0 %[when=%fortran]fortran=gcc@12.5.0"
      variants: cuda_arch=80
      target: [zen2]
  modules:
    prefix_inspections:
      ./lib64: 
        - LD_LIBRARY_PATH
      ./lib: 
        - LD_LIBRARY_PATH
    default:
      roots:
        tcl: $spack/../install/$date/modules
      enable: [tcl]
      tcl:
        hash_length: 0
        projections:
          all: '{name}/{version}/{hash:4}'
        all:
          autoload: none
          conflict:
            - '{name}'
          environment:
            set:
              '{name}_ROOT_DIR': '{prefix}'
  specs:
    - binutils+gold
    - gcc@=12.5.0+binutils~bootstrap+strip languages=c,c++,fortran,jit %gcc@=8.5.0
    - gcc@=15.1.0+binutils~bootstrap+strip languages=c,c++,fortran,jit
    - gcc@=14.3.0+binutils~bootstrap+strip languages=c,c++,fortran,jit
    - gcc@=13.4.0+binutils~bootstrap+strip languages=c,c++,fortran,jit
    - gcc@=12.5.0+binutils~bootstrap+strip languages=c,c++,fortran,jit
    - gcc@=11.5.0+binutils~bootstrap+strip languages=c,c++,fortran,jit
    - gcc@=10.5.0+binutils~bootstrap+strip languages=c,c++,fortran,jit
    - gcc@=9.5.0+binutils~bootstrap+strip languages=c,c++,fortran,jit
    - gcc@=8.5.0+binutils~bootstrap+strip languages=c,c++,fortran,jit
    - go@=1.24.3
    - llvm@=20.1.6+clang+flang+python
    - llvm@=19.1.7+clang+flang+python
    - llvm@=18.1.8+clang+flang+python
    - llvm@=17.0.6+clang+flang+python
    - llvm@=16.0.6+clang+flang+python
    - llvm@=15.0.7+clang+flang+python
    - llvm@=14.0.6+clang+flang+python
    - environment-modules
    - screen
    - aspell
    - bc
    - bison
    - bzip2
    - ccls
    - cmake
    - cppcheck
    - curl
    - flex
    - ffmpeg
    - fftw
    - emacs+tls+treesitter+json
    - git
    - gdb
    - gnuplot
    - gnutls
    - htop
    - hunspell
    - imagemagick
    - libxml2
    - likwid
    - ninja
    - npm
    - mercurial
    - makedepend
    - patch
    - pkg-config
    - python
    - rsync
    - screen
    - stow
    - strace
    - texinfo
    - texlive
    - tmux
    - unzip
    - vim+python+cscope features=huge
    - wget
    - zsh
    - global
    - xterm
    - py-numpy
    - py-matplotlib
    - py-pandas
    - py-nose
    - py-autopep8
    - py-flake8
    - py-jedi
    - py-pip
    - py-pyyaml
    - py-seaborn
    - py-sphinx
    - py-scipy
    - py-yapf
    - py-yt
    - py-torch+cuda+cudnn+magma+nccl
    - py-tensorflow+cuda+nccl
    - masa~python
    - valgrind~mpi
    - ascent
    - nccmp
    - netcdf-fortran
    - amrvis dims=3
    - amrvis+profiling dims=2
    - mpich
    - hdf5+hl+cxx
    - parallel-netcdf
    - paraview+hdf5+visitbridge+mpi
    - visit~gui
    - netcdf-c
    - boost
    - hypre
    - h5z-zfp
    - yaml-cpp
    - cuda@=12.9.0
    - cuda@=12.8.1
    - cuda@=12.6.3
    - cuda@=12.5.1
    - cuda@=12.4.1
    - cuda@=12.3.2
    - cuda@=12.2.2
    - cuda@=12.1.1
    - cuda@=11.8.0
    - cuda@=11.7.1
    - cuda@=11.6.2
    - cuda@=11.5.2
    - cuda@=11.4.4
