packages:
  mpi:
    require: "mpich"
  blas:
    require: "openblas"
  lapack:
    require: "openblas"
  c:
    require: "apple-clang"
  cxx:
    require: "apple-clang"
  fortran:
    require: "gcc"
