packages:
  emacs:
    require: "+tls+native+treesitter+json"
  gcc:
    require: "~bootstrap+strip languages=c,c++,fortran,jit"
  hdf5:
    require: "+hl+cxx"
  llvm:
    require: "+clang+flang+python"
  texlive:
    require: "scheme=full"
  vim:
    require: "+python+cscope features=huge"
  mpi:
    require: "mpich"
  blas:
    require: "openblas"
  lapack:
    require: "openblas"
  c:
    require: "apple-clang"
  cxx:
    require: "apple-clang"
  fortran:
    require: "gcc"
