spack:
   view: false
   include:
   - ./packages.yaml
   - ./modules.yaml
   - ./config.yaml
   definitions:
   - compilers: ["%apple-clang"]
   - core:
     - cmake
   specs:
   - matrix:
     - [$core]
     - [$compilers]
